services: 
  fp-svc:
    build:
      context: .
      additional_contexts:
      # GIT REPO: git@github.com:pablopratt12/itp-docker.git
        - final-project=git@github.com:pablopratt12/itp-docker.git
    image: pablopratt12/final-project-image:docker-compose-build-tag
    container_name: fp-c
    ports:
      - 8081:80
    volumes:
      - ./volumes/final-project/config/conf.d:/etc/nginx/conf.d
      - ./volumes/final-project/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hp-svc
  hp-svc:
    image: nginx.alpine3.21
    container_name: hp-c
    volumes:
      - ./volumes/final-project/config/conf.d:/etc/nginx.conf.d
      - ./volumes/final-project/config/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/final-project/html:/usr/share/nginx/html
  watchdog-svc:
    image: alpine:3.21.3
    container_name: watchdog-c
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - fp-svc



  